#!/usr/bin/env bash
# install nginx web server on new ubuntu server

sudo apt update
sudo apt -y install nginx
echo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
