#!/usr/bin/env bash
# installs haproxy and configures it
sudo apt -y update
sudo apt -y install haproxy

echo "
frontend web-frontend
   bind *:80
   mode http
   default_backend web-backend

backend web-backend
   balance roundrobin
   server 193365-web-01 100.25.12.87:80 check
   server 193365-web-02 18.208.120.10:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod +x /etc/init.d/haproxy
sudo service haproxy restart
