#!/usr/bin/env bash
# this script creates a backup file and archive

Date=$(date +%d-%m-%Y)
archive_file="$Date.tar.gz"

mysqldump -u root -p"$1" --all-databases > "backup.sql"

tar -czf "$archive_file" "backup.sql"
